### ISSUE TITLE
Update database scripts

### ISSUE THREAD

**Issue by Runi-VN** [HrBjarup/Fog-Carport#38]
## DDL (Create script)
Discuss the following (Mentioned [here](https://github.com/HrBjarup/Fog-Carport/wiki/Week-5-%7C-Second-sprint#this-weeks-progress))  
* Orders.status => ENUM?
* Orders.shed_walls_id & Orders.shed_floor_id => use? change?
* Should we set a default value for `Orders.shed_walls_id` &  `Orders.shed_floor_id`?

Currently:
`Orders.status` is a VARCHAR 
`Orders.shed_walls_id` & `Orders.shed_floor_id` are integers refering to the database ID of the material related to either wall or floor.

## DML (insertion script)
@Castau has some changes to the DML (in regards to the raised roof calculation)
@MalteMagnussen probably has some different types of materials for ```skur beklædning```
@Runi-VN has to update materials for different types of roofing meant for flat roof calculation.

**Comment by Runi-VN** [comment]
I think:
Ideally we should change `Orders.status` to an ENUM. If not:
Lets keep `Orders.status` as a varchar, but lets define the possible states:
* Processing (Order received, waiting on seller)
* Awaiting (Bill sent, awaiting customer)
*((Payment received))*
* Verified (Continue to send rest of order)
* Finished (Order finished)  

(This is just a draft, please assist in possible names, states, etc)

`Orders.shed_walls_id` & `Orders.shed_floor_id` are fine as they are, but the id `0` should be used as **default value** and can be used to determine whether or not a client wants these parts.

**Comment by MalteMagnussen** [comment]
"* Orders.shed_walls_id & Orders.shed_floor_id => use? change?"

Currently using these in the Advanced Shed Algorithm.

**Comment by MalteMagnussen** [comment]
* "Should we set a default value for Orders.shed_walls_id & Orders.shed_floor_id?"
Currently the advanced shed algorithm just assumes that the input for these two values is correct or 0 for floor_id.

So somewhere before it reaches ShedLogic.java this has to be checked or caught or something.

I assume, that since shed is optional entirely, that the ShedLogic.java is not even called if the shed values are empty for an order.

**Comment by MalteMagnussen** [comment]
"Orders.shed_walls_id & Orders.shed_floor_id are fine as they are, but the id 0 should be used as default value and can be used to determine whether or not a client wants these parts."

I think java defaults them to 0 anyway, since they're ints on the entity, but I agree that they should be NOT NULL DEFAULT 0 anyway in the DB. 

I check for the floor by matching against 0.

**Comment by MalteMagnussen** [comment]
> @MalteMagnussen probably has some different types of materials for skur beklædning

Type of wood used for the shed "beklædning" is a field on the Order. It's an int field. It references the ID of the wood in the DB. So whatever ID you send along to ShedLogic.java is the type of wood that will be used for the beklædning.

**Comment by Runi-VN** [comment]
Initial fix suggestion:

**Comment by MalteMagnussen** [comment]
@Runi-VN Can we close this issue?

**Comment by Runi-VN** [comment]
Most here is fixed. Other is copied to next issue following technical meeting 01/05-2019.
Continued here:
https://github.com/HrBjarup/Fog-Carport/issues/44
